### ISSUE TITLE
Enable different tolerances for Exodiff "combined" test

### ISSUE THREAD

**Issue by joshuahansel** [sandialabs/seacas#100]
Currently, Exodiff offers a "combined" test, in addition to "absolute" and "relative". From comments in the code, it appears that the ultimate desired implementation would be able to do the following:
 ```
|x - y| < max(tol_abs, tol_rel * max(|x|, |y|))
```
Basically I interpret this as checking whether the error is within the relative tolerance *or* the absolute tolerance. However, it appears that the current implementation assumes
```
tol_abs = tol_rel
```
Personally I find that with this assumption, the "combined" test is not useful at all, since it involves a blind absolute error test that knows nothing of the magnitude of the values being compared. However, if the `tol_abs = tol_rel` assumption were removed, I would find the "combined" test to be very useful (I'd probably use it exclusively in fact).

The issue with the current implementation is this: ideally I'd like to perform relative error checks on all of my values. However, we live in a real world with finite precision and roundoff error, so a relative check on small values often diffs simply because these "machine errors" are present. What I would like to do when comparing values is
```
(rel_err < rel_tol) OR (abs_err < abs_tol)
```
Instead, I am forced to use Exodiff's "floor" value approach, which means that for small values, I basically don't do any comparison at all. For example, with a relative error check with a tolerance of 1e-6, I have values greater than 1e-9 that I am forced to floor, even though their absolute errors are around 1e-15.

If this capability were implemented, I think that an intuitive command file syntax, would for example be the following:
```
NODAL VARIABLES relative 1e-6 absolute 1e-14
```
instead of having something called "combined". This was the first thing I tried blindly when trying to accomplish the "relative error OR absolute error" test.

Also, I'd like to note that in the documentation (the report "A Collection of Exodus Utilities"), there appears to be no guidance on how the "combined" check is enabled in the command file. I only see the command-line switch for enabling the default test type.

**Comment by gsjaardema** [comment]
Thanks for the feedback.  

I will take a look at adding the "combined" check documentation to the report.

The current combined check comes from http://realtimecollisiondetection.net/blog/?p=89.  You are correct that the more general version has different values for `tol_abs` and `tol_rel`.  For expediency (all other tolerance types have a single tolerance value), and based on the usage in the referenced blog entry, I implemented the combined tolerance with `tol_abs == tol_rel` with a comment to sometime look at supporting distinct values.

I will take a look at doing this; not sure when I will be able to get to it though.

**Comment by joshuahansel** [comment]
Auto-closing issues, huh? That's one way to close issues :) I wonder if it'll re-open with this comment!

**Comment by gsjaardema** [comment]
Yes, I tried some new bot on github and didn't realize it would close the issues...

**Comment by joshuahansel** [comment]
Hi @gsjaardema could we reopen this issue? If I addressed this issue, would there be someone with the availability to review it? If so, I'd discuss a design plan here before undertaking.
