### ISSUE TITLE
Override specific exodiff tolerances at the command line

### ISSUE THREAD

**Issue by bwspenc** [sandialabs/seacas#122]
It would be very helpful to be able to override tolerances of specific variables at the command line.  Currently, we have to create an 'exodiff' file to override tolerances of any variables, which is fine if there are a lot of variables that need to be tweaked. We often have cases where we just need to tweak the tolerances on one or two variables, in which case command line arguments would be less cumbersome for use in our testing scripts.

**Comment by bwspenc** [comment]
@gdsjaar Hi from Idaho Falls!  I'm glad to see that you're keeping SEACAS alive and well! We use exodiff heavily in our testing of MOOSE.

I'm curious how hard you think this would be to implement. This definitely falls under the category of 'nice to have' features -- we're getting along just fine without it, but it would help clean up things.

**Comment by gsjaardema** [comment]
There is currently the `--tolerance <value>` option.  I'm assuming you want something more granular where you can specify a tolerance for specific variables -- `--tolerance SIG*=1.0e-5, DISP*=1.0e-4`

That would probably be reasonably simple to implement, but no guarantee on the timeframe.

**Comment by bwspenc** [comment]
Exactly.  Something like that for variable-specific -tolerance, -absolute, -relative, and -combined. 

Question: in your suggested syntax of  `--tolerance SIG*=1.0e-5`, what is the meaning of `*` in `*=`? It seems like it would be clearer with simply something like `--tolerance SIG=1.0e-5`.

Also, do the current `-tolerance` and `-relative` options do the same thing?

**Comment by gsjaardema** [comment]
The `SIG*` was meant to be a regular expression which would match `SIGXX, SIGYY, SIGZZ, ..., SIGXY'.   I think implementing it with regular expression would make it more useful.

Currently, `-tolerance <value>` specifies the default value used in the tolerance comparison. `-absolute` and `-relative` and `-combined` specify whether the default tolerance type is absolute or relative or combined

**Comment by bwspenc** [comment]
Oh, I see.  I was thinking it was a times-equal sort of operation. Yes, being able to use regular expressions there would be great.
