### ISSUE TITLE
More native functionality for quadrature points

### ISSUE THREAD

**Issue by GregVernon** [sandialabs/seacas#185]
Currently, variables associated with quadrature points are written to variables with indexed names, where the indices represent the quadrature point index -- for example stress_xx_1,  stress_xx_2, stress_xx_3,...   stress_xx_8 for a 2x2x2 quadrature scheme.  This can get confusing in simulations where blocks have different quadrature schemes.

A possible extension to Exodus could be to allow for a more organized means for writing values to quadrature points.

**Comment by gsjaardema** [comment]
There is an option that the application can specify the suffices to be used for multi-component fields. The IOSS call to define the field and its suffix list is `create_named_suffix_field_type` in `Ioss_VariableType.h`  However, this only works for the "non-composite fields" similar to vector, tensor, ...  For the "composite fields" which is what a tensor+quadrature points type field in your example is, IOSS is currently limited to using a "named field" plus a "numbered-suffix" field.

I'm not sure how much effort it would be to make composite fields work with two "named fields" which would make it possible to define a more logical mapping from suffix to quadrature point location.  I will try to take a look...

**Comment by gsjaardema** [comment]
See https://github.com/gsjaardema/seacas/wiki/Discontinuous-Galerkin
