### ISSUE TITLE
Exported targets are missing include directories in usage requirements

### ISSUE THREAD

**Issue by mathstuf** [sandialabs/seacas#239]
The exported targets from (at least) the `ioss` library is missing include directories. This means that just doing `target_link_libraries(mytgt PRIVATE Ioss)` is not sufficient to use it; instead `SEACASIoss_INCLUDE_DIRS` must be manually used. Instead, each target should provide this as part of its usage requirements automatically.

Cc: @utkarshayachit

**Comment by gsjaardema** [comment]
PR welcomed...

**Comment by gsjaardema** [comment]
Or more information.  IOSS has primarily been used internally, so I don't have much experience with what is needed to make it easier to use for external packages.  Willing to learn...

**Comment by mathstuf** [comment]
It's all wrapped up in the TriBITS package logic. I suspect that the new TriBITS stuff should make the installed targets more useful, but I'm not sure.

I am able to make use of what is installed at least by manually adding the include directory at the expense of the `VTK::ioss` target not being as useful once VTK is installed…which is not really a concern. But it'd be nice if it could be consumed just by its target name.

**Comment by gsjaardema** [comment]
OK, that makes sense.  Is there anything I can do to workaround the TriBITS logic for just Exodus and IOSS that would help you?  Maybe selectable via a setting?

**Comment by mathstuf** [comment]
You can do this:

```cmake
target_include_directories(Ioss INTERFACE "$<INSTALL_INTERFACE:${include_install_dir}>")
```

where `${include_install_dir}` is whatever TriBITS passes to `DESTINATION` for the header installation. Repeat for other library targets as necessary.

**Comment by gsjaardema** [comment]
The TriBITs was updated and hopefully addresses this issue.

**Comment by gsjaardema** [comment]
This should have been fixed by the TriBITs update.  We can reopen if it is till a problem.
