### ISSUE TITLE
Issue building newer SEACAS with spack

### ISSUE THREAD

**Issue by wortiz** [sandialabs/seacas#342]
No packages are built with the seacas@2022-10-14 snapshot or seacas@master

2022-05-16 still seems to work so I'm guessing the issue is coming from CMake changes in SEACAS

[spack-build-01-cmake-out.txt](https://github.com/sandialabs/seacas/files/9911611/spack-build-01-cmake-out.txt)

**Comment by gsjaardema** [comment]
I think the issue is that the project name was changed from `SEACASProj` to `Seacas` but I didnt' update the spack `package.py` file.  

I will have to figure out how to make this change version specific...
Sorry for the trouble; thanks for letting me know.

**Comment by gsjaardema** [comment]
Should be fixed when https://github.com/spack/spack/pull/33646 is merged.

**Comment by gsjaardema** [comment]
Let me know if this works/doesn't work for you.  Changes have been merged into spack, so if you update spack, it should build for you now.

Sorry for the trouble.

**Comment by wortiz** [comment]
Thanks. This appears to be fixed now.
