### ISSUE TITLE
problem in windows: Windows build does not use getsubopt yet

### ISSUE THREAD

**Issue by wphu** [sandialabs/seacas#357]
I want to decomp a exodus II mesh in Windows.

I run: nem_slice -e -S  -l multikl -c -o xxx.g.nem -m mesh=10 xxx.g

then I have the error:  Windows build does not use getsubopt yet.

Can this problem be solved?  It would be better if someone could provide a solution.

Thanks

**Comment by gsjaardema** [comment]
Can you pull the current source and see if that fixes the nem_slice problem for you.

**Comment by wphu** [comment]
OK, I will try it.

**Comment by wphu** [comment]
> Can you pull the current source and see if that fixes the nem_slice problem for you.

I have tried, and the current source fixes the problem. Thank you very much.
