### ISSUE TITLE
Iogn_DashSurfaceMesh.h: ExodusData() default ctor causes clang warnings

### ISSUE THREAD

**Issue by japlews** [sandialabs/seacas#398]
Can the default constructor for ExodusData() be removed? It causes many warnings on Clang 14+ builds, since const members will not be initialized appropriately when the object is default-constructed:

https://github.com/sandialabs/seacas/blob/1f5c7e6de58c4bde72f627a48769a966aaf1c21c/packages/seacas/libraries/ioss/src/generated/Iogn_DashSurfaceMesh.h#L68C28-L68C28

Thanks!
Julia

**Comment by gsjaardema** [comment]
Done.  See commit https://github.com/sandialabs/seacas/commit/6e0f3601dd47751a0c9589e7e5b1d821f945f383

**Comment by japlews** [comment]
Thanks @gsjaardema
