### ISSUE TITLE
What do I use instead of ex_get_side_set()?

### ISSUE THREAD

**Issue by knepley** [sandialabs/seacas#401]
The function ex_get_side_set() is deprecated, but nothing in the message gives its replacement. I also cannot find anything about this in the documentation. Where do I look?

  Thanks,

    Matt

**Comment by gsjaardema** [comment]
See https://sandialabs.github.io/seacas-docs/html/ex__get__side__set_8c.html#ac96dfd540bec6ecfdfafaa90fdc25276 for this specific function.  

All deprecated functions and there replacements are shown at https://sandialabs.github.io/seacas-docs/html/deprecated.html

The general SEACAS documentation site is https://sandialabs.github.io/seacas-docs/sphinx/html/index.html

**Comment by knepley** [comment]
Great! Thanks Greg
