### ISSUE TITLE
Ioss includes own headers with `<>`

### ISSUE THREAD

**Issue by mathstuf** [sandialabs/seacas#415]
This requires that an explicit `-I` be passed for the headers to find each other. It would be better if the library could include its own headers using `""` paths relative to the header itself.

**Comment by gsjaardema** [comment]
Yes, that is probably a good idea.  At one time, we had a build system where the `<>` includes were required or strongly recommended, but that is no longer being used and the current includes use a mismash of `""` and `<>`.

**Comment by gsjaardema** [comment]
Does #423 address this issue.  It has been merged.

**Comment by mathstuf** [comment]
Looks OK to me; I'll be back if we find an issue (next time we bump IOSS). I'll leave you to close according to your workflow.
