### ISSUE TITLE
How to instantiate a transform?

### ISSUE THREAD

**Issue by spyridon97** [sandialabs/seacas#433]
In the past, Iotr::Factory was part of Ioss_transform.h.

This has been moved in Iotr_Factory.h

Are we supposed to include Iotr_Factory.h to create a transform such as

```c++
    auto transform = std::unique_ptr<Ioss::Transform>(Iotr::Factory::create("offset"));
    transform->set_property("offset", -1);
``` 

Or is there another way, such that we don't need to include?

**Comment by spyridon97** [comment]
maybe it would be convenient to have a create factory function in ioss_transform.h. which internally would return a Iotr::Factory.

**Comment by gsjaardema** [comment]
Yes, maybe `Ioss::Transform *Ioss::create_transform(const std::string &transform_type)`

**Comment by spyridon97** [comment]
Maybe you could have Ioss::TransformFactory like Ioss::IOFactory. And remove Iotr::Factory.

**Comment by gsjaardema** [comment]
See #434

**Comment by gsjaardema** [comment]
I tihnk this can be closed.  Please reopen if still problems with the fix.
