### ISSUE TITLE
testwt-assembly.c: Error c2057 when building with MSVC and NetCDF binaries are found

### ISSUE THREAD

**Issue by johnwparent** [sandialabs/seacas#438]
[`testwt-assembly.c`:ln 95](https://github.com/sandialabs/seacas/blob/master/packages/seacas/libraries/exodus/test/testwt-assembly.c#L95) raises [error c2057](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2057?view=msvc-170) when Seacas is compiled under MSVC (tested with VS 16 + 17). 

This is due to the use of a variable in an array declaration, which is invalid for the MSVC C compiler.
This is not observed on the Seacas Windows CI as NetCDF binaries are not installed on the CI system and the CMake command that adds `testwt-assembly.c` as an executable is hidden behind a logical check for `ncdump.exe`.
This is observed primarily with package managers like Spack or from source builds of NetCDF on the Windows platform that vendor the NetCDF bin utilities.

Simply leaving the test out of the build allows the rest of Seacas to compile and link as expected.
See [the Spack package patch](https://github.com/spack/spack/pull/42692/files#diff-bc0e25673979a3ad4dc8055b1850f52ce0539523749233b6ea87b048eb6b26a4) for an example.

Happy to make whatever code/CMake changes need to be made myself, particularly if testing local changes on Windows is inaccessible to you folks.

**Comment by gsjaardema** [comment]
Thanks.  I will just replace the `num_elem_blk` with its value of 7.  Not recommended programming style for general use, but should be ok in this test code.

**Comment by johnwparent** [comment]
Works for me, thanks!

**Comment by gsjaardema** [comment]
See [29a9ebe](https://github.com/sandialabs/seacas/commit/29a9ebeccb5a656b4b334fa6af904689da9ffddc)
