### ISSUE TITLE
[MSVC][c++20][c++latest] Ioss_DatabaseIO.C failed with error 7525: call to immediate function is not a constant expression

### ISSUE THREAD

**Issue by NEIL-smtg** [sandialabs/seacas#475]
I work on MSVC compiler testing, and we regularly build popular open-source project such as VTK. VTK uses this repo as one of the third-party modules. 

I have reported this issue at [VTK #19415](https://gitlab.kitware.com/vtk/vtk/-/issues/19415). I believe the problematic line that is https://github.com/sandialabs/seacas/blob/abc1a6b58d77bd62f255bd93b2950d3e017c3848/packages/seacas/libraries/ioss/src/Ioss_DatabaseIO.C#L1641
  
We have encountered the following errors when building VTK with MSVC under the c++20 and c++latest mode:

```c++
vtk\ThirdParty\ioss\vtkioss\Ioss_DatabaseIO.C(1643,28): error C7595: 'vtkfmt::v10::basic_format_string<char,double &,char &>::basic_format_string': call to immediate function is not a constant expression [C:\gitP\vtk\vtk\build_amd64\ThirdParty\ioss\vtkioss\ioss.vcxproj]

vtk\ThirdParty\ioss\vtkioss\Ioss_Utils.C(1381,20): error C7595: 'vtkfmt::v10::basic_format_string<char>::basic_format_string': call to immediate function is not a constant expression [C:\gitP\vtk\vtk\build_amd64\ThirdParty\ioss\vtkioss\ioss.vcxproj]
C:\gitP\vtk\vtk\ThirdParty\ioss\vtkioss\Ioss_Utils.C(1381,20): failure was caused by a read of a variable outside its lifetime
C:\gitP\vtk\vtk\ThirdParty\ioss\vtkioss\Ioss_Utils.C(1381,20): see usage of 'suffix'
```

Step to reproduce:

1. Download the preprocessed file [Ioss_DatabaseIO.txt](/-/project/13/uploads/3afd317d575045a256862d153356db09/Ioss_DatabaseIO.txt)
2. Run the following command: `cl /c /TP /EHsc /std:c++20 Ioss_DatabaseIO.txt`

**Comment by gsjaardema** [comment]
I think these are now fixed; I was not able to reproduce the errors, but I think I understand what is causing them and have comitted a fix in 80470e6

**Comment by spyridon97** [comment]
@NEIL-smtg can you verify that these fixes have fixed your issue?

**Comment by NEIL-smtg** [comment]
@spyridon97 yes, I can confirm that both errors has been fixed.

**Comment by NEIL-smtg** [comment]
Closing this issue, since the errors have been fixed
