### ISSUE TITLE
[URGENT] Exonull does not compile with SEACAS_HAVE_MPI ON on Windows

### ISSUE THREAD

**Issue by spyridon97** [sandialabs/seacas#478]
In paraview superbuild we tried to build the new seacas that includes exonull but we failed to do so on windows.

That's the error we got:

https://gitlab.kitware.com/paraview/paraview-superbuild/-/merge_requests/1218#note_1554860

This is blocking the release of ParaView 5.13-RC2

**Comment by spyridon97** [comment]
@gdsjaar

**Comment by gsjaardema** [comment]
I will take a look.  Disabling exonull might be the quickest/easiest fix since it it only used for testing.

It may be missing all of the EXPORT's that were added on the other datbase types?

**Comment by gsjaardema** [comment]
I modified the develop version of seacas to allow enabling/disabling the building of exonull:
```
-D ENABLE_ExoNull:BOOL=YES \
```
It default to `YES` in the cmake-config script that we use, but otherwise should be off by default.

**Comment by spyridon97** [comment]
Could create a commit in which you add all the exports and test it please?

**Comment by gsjaardema** [comment]
It looks (on a quick look) that it already has the exports...

**Comment by spyridon97** [comment]
The SECAS_HAVE_EXONULL did properly disable the module, i although i would suggest for this to be fixed.

I will leave it up to you if you wanna close the issue or not.

**Comment by gsjaardema** [comment]
Do you know what exports are missing?  It seems to follow the patter of the exodus Ioex_DecompositionData.h exactly so I'm not sure what is missing...

**Comment by spyridon97** [comment]
I have no clue to be honest.

**Comment by gsjaardema** [comment]
I will close this issue and we can figure out what is the root problem some time later if it becomes important.
